// <auto-generated />
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProjetoJogo.Migrations
{
    [DbContext(typeof(JogoContext))]
    partial class JogoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("API.Models.Escolha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("JogadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpcaoEscolhida")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.ToTable("Escolhas");
                });

            modelBuilder.Entity("API.Models.FinalJogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoFinal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Finais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TipoFinal = "Final Indefinido"
                        },
                        new
                        {
                            Id = 2,
                            TipoFinal = "Final Bom"
                        },
                        new
                        {
                            Id = 3,
                            TipoFinal = "Final Ruim"
                        },
                        new
                        {
                            Id = 4,
                            TipoFinal = "Morte"
                        });
                });

            modelBuilder.Entity("API.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinalJogoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinalJogoId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("API.Models.Escolha", b =>
                {
                    b.HasOne("API.Models.Jogador", "Jogador")
                        .WithMany("Escolhas")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("API.Models.Jogador", b =>
                {
                    b.HasOne("API.Models.FinalJogo", "FinalJogo")
                        .WithMany()
                        .HasForeignKey("FinalJogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinalJogo");
                });

            modelBuilder.Entity("API.Models.Jogador", b =>
                {
                    b.Navigation("Escolhas");
                });
#pragma warning restore 612, 618
        }
    }
}
